services:
  - type: web
    name: hyd-aqi-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HOPSWORKS_API_KEY
        sync: false
      - key: HOPSWORKS_PROJECT
        sync: false
      - key: LATITUDE
        value: "25.3792"
      - key: LONGITUDE
        value: "68.3683"
      - key: TIMEZONE
        value: "Asia/Karachi"
    healthCheckPath: /health